# Generated by Django 4.0.3 on 2022-04-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_remove_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='idarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.articulos'),
        ),
    ]
