# Generated by Django 4.0.3 on 2022-04-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_alter_pedido_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='idarticulo',
        ),
    ]
