# Generated by Django 4.0.4 on 2022-04-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_remove_pedido_cantidad_remove_pedido_idarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle',
            field=models.ManyToManyField(to='AppCoder.articulos'),
        ),
    ]
