# Generated by Django 4.0.4 on 2022-04-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_pedido_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='detalle',
        ),
    ]
