# Generated by Django 4.0.4 on 2022-04-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombre',
        ),
        migrations.AddField(
            model_name='clientes',
            name='contacto',
            field=models.CharField(default='-', max_length=50, verbose_name='contacto'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='domicilio',
            field=models.CharField(default='-', max_length=50, verbose_name='domicilio'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='AppCoder.articulos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCoder.articulos'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCoder.pedido'),
        ),
        migrations.AlterField(
            model_name='pedido_temp',
            name='idarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppCoder.articulos'),
        ),
    ]
