# Generated by Django 4.0.4 on 2022-04-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0014_remove_clientes_apellido_remove_clientes_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
