# Generated by Django 4.0.4 on 2022-04-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_alter_clientes_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
