# Generated by Django 4.0.4 on 2022-04-26 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCoder', '0017_avarat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avarat',
            new_name='Avatar',
        ),
    ]
